### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by matejkramny** [ansible-semaphore/semaphore#325]
This document will be updated regularly as things go along. If you want to add features or nudge things, open another issue or contact us on discord.

**Semaphore features**

- [ ] Ask the user via websocket if there are any prompts in ansible
- [ ] Remote inventories #47
- [ ] Implement ssh keys with passphrase (like prompts)
- [ ] Implement ansible vaults
- [ ] Quick fire tasks from the UI
- [ ] Some sort of tutorial mode in the UI
- [ ] Real user privileges #344 
- [ ] Edit settings from the UI? First setup happens in the UI? Metabase, Piwik have wonderful non-CLI setup wizards #354 
- [ ] API Token UI (so far only API endpoints exist)
- [ ] Remove git repo requirement for templates #327

**Codebase todos**

- [x] Get rid of `gin` in favour of native `http` + `gorilla/mux`
- [ ] Support https and letsencrypt
- [ ] Use docopt for CLI arguments
- [ ] Add tools to CLI so it's easier to add users, etc
- [ ] Get rid of bindata if possible
- [ ] Upgrade to bootstrap 4
- [ ] Upgrade to angular 2 (might not be worth doing)
- [ ] SQLite support #238
- [ ] Make API documentation up to date
- [ ] Create test cases for the API (only for more complicated API endpoints)
- [ ] Verify upgrade via GPG #373
- [ ] Cancel running playbook task #392

**older roadmap:** #72
