### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by matejkramny** [ansible-semaphore/semaphore#72]
> The goal of this is to create a super-simple interface which is capable of configuring majority of ansible, and for those who have 'extra needs' there will be option to configure the command line params per task.
>
> The need for v2 is also to improve deployment & maintainability of the project.

#### 2.0

- [x] SSH key storage / to download playbook & authenticate to hosts
- [x] Projects - Users can join projects / can collaborate as team with permissions
- [x] Static inventory
- [x] Define extra (environment) vars to tasks
- [x] Able to create custom ansible jobs by defining parameters (infinite usabilities for user here)
- [x] Timestamp output from ansible
- [x] API Tokens (#43, #19)
- [x] [API Documentation](https://ansible-semaphore.github.io/semaphore)
- [ ] Event stream
- [x] Task history
- [ ] Auto-update

### 2.1
- [ ] API Token UI
- [ ] Store AWS/Google/DO/? keys
- [ ] Dynamic inventory - AWS/DO/Google/? (#47)
- [ ] Store vault passwords

### 2.2

- [ ] Cron-job scheduling of tasks
- [ ] Graphs & Stats :)
- [ ] Analyse job durations & tasks executed
- [ ] IDEA: Split up output per task/section (identified when `***` occurs on a line) for grater control
- [ ] Parallel jobs
- [ ] AMI (basically start the AMI, which pre-configures itself for SSH using letsencrypt and auto-updates the binary) - one click install of semaphore
